api/urls.py
from django.urls import path, include
from .views import ProductoList,ProductoDetalle


urlpatterns = [
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>', ProductoDetalle.as_view(), name='producto_detalle'),

]

bases/urls.py
from django.urls import path
from bases.views import Home
from bases.views import HomeSinPrivilegios
from django.contrib.auth import views as auth_views

#incluye la plantilla inmersa en la clase home
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

proyectoDs2/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static


#define las urls paternas para incluirlas
urlpatterns = [
    path('',include(('bases.urls', 'bases'), namespace='bases')), #ruta principal
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')), #ruta para inventarios
    path('proveedores/', include(('proveedores.urls', 'proveedores'), namespace='proveedores')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls), #ruta para ventana admin
 ]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey

# se crean los parametros que tendra la tabla estado,fechaCreacion,fechaModificacion,usuarioCreado,usuarioModificado
class Modelado(models.Model):
    estado = models.BooleanField(default=True)

    # se actualiza unicamente cuando el registro se cree
    fechaCreacion = models.DateTimeField(auto_now_add=True)

    #se coloca cada vez que haya una modificacion
    fechaModificacion = models.DateTimeField(auto_now=True)

    usuarioCreado = models.ForeignKey(User, on_delete=models.CASCADE)
    usuarioModificado = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True


class Modelado2(models.Model):
    estado = models.BooleanField(default=True)

    # se actualiza unicamente cuando el registro se cree
    fechaCreacion = models.DateTimeField(auto_now_add=True)

    #se coloca cada vez que haya una modificacion
    fechaModificacion = models.DateTimeField(auto_now=True)

    usuarioCreado = UserForeignKey(auto_user_add=True, related_name='+')
    usuarioModificado = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        abstract=True

bases/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


# la clase home hereda de generic el TemplateView y tambien loginremixin(van siempre a la izq)
class Home(LoginRequiredMixin, generic.TemplateView):
    # asi se le va a llamar a la plantilla
    template_name = 'bases/home.html'

    #obliga a que el usuario se loguee para ver contenido.
    login_url = 'bases:login'

# redirige a la plantilla
class HomeSinPrivilegios(generic.TemplateView):
    login_url = 'bases:login'
    template_name = 'bases/sin_privilegios.html'


# hereda y aplica funcionalidad
class SinPrivilegios(LoginRequiredMixin, PermissionRequiredMixin):
    login_url = 'bases:login'
    raise_exception = False
    redirect_field_name = 'redirect_to'

    def handle_no_permission(self):
        # ********************
        # CONFIGURAR USUARIO ANONIMO QUE INGRESE CON EL LINK DEL APLICATIVO
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user == AnonymousUser():
            self.login_url = 'bases:sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))

bases/templates/bases/home.html
{#muestra el contenido del html mencionado#}
{%  extends 'base/baseTotalidad.html' %}

{% comment %}      {% block side_bar %} {% endblock %}  anula el bloque sidebar     {% endcomment %}

bases/templates/bases/login.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block side_bar %} {% endblock side_bar %}
{% block top_bar %}  {% endblock top_bar %}
{% block page_content %} {% endblock page_content %}
{% block footer %}   {% endblock footer %}


{% block login %}
    <div class="container">



        <!-- Outer Row -->
        <div class="row justify-content-center align-content-center my-5 py-5">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5 sombra-caja scrolli">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4 sombra-texto">Inicio de Sesión</h1>
                                        <small class="text-danger">

                                            {#MANEJO DE ERRORES#}
                                            {% if form.errors %}
                                                {% for field in form %}
                                                    {% if field.errors %}
                                                        {% for error in field.errors %}
                                                            {{ error|escape }}
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}

                                            {% if form.non.field_errors %}
                                                {% for field in form.non.field_errors %}
                                                    {{ error|escape }}
                                                {% endfor %}
                                            {% endif %}


                                        </small>
                                    </div>
                                    <form class="user" method="POST">

                                        {# etiqueta de seguridad #}
                                        {% csrf_token %}

                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user sombra-texto" id="id_username"
                                                   name="username" placeholder="Ingresa tu usuario">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user sombra-texto"
                                                   id="id_password" name="password" placeholder="Ingresa tu contraseña">
                                        </div>

                                        <button type="submit" class="btn btn-facebook btn-user btn-block"> Acceder
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>



    </div>
{% endblock %}

{% block js_page %}
    <script>
        {#MANEJO DE ERRORES#}
        {% if form.errors %}
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        mensaje('{{ error|escape }}', 'red');
                    {% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if form.non.field_errors %}
            {% for field in form.non.field_errors %}
                mensaje('{{ error|escape }}', 'red');
            {% endfor %}
        {% endif %}

    </script>
{% endblock %}

bases/templates/bases/sin_privilegios.html
{% extends 'base/baseTotalidad.html' %}

{% block page_content %}

    <div class="col-sm-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Acceso denegado</h5>
                <p class="card-text">No tienes privilegios para acceder a este recurso</p>
                <div class="text-xs font-weight-bold text-primary text-uppercase m-3">
                    Usuario:
                    <mark> {{ user.username }} {{ user.get_full_name }}</mark>
                </div>
                <div class="dropdown-diviver"></div>
                <a href="{% url 'bases:home' %}" class="btn btn-primary">Ir a Inicio</a>
                <a href="{% url 'bases:login' %}" class="btn btn-secondary">Ingresar con otro usuario</a>
            </div>
        </div>
    </div>

{% endblock %}