api/urls.py
from django.urls import path, include
from .views import ProductoList,ProductoDetalle


urlpatterns = [
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>', ProductoDetalle.as_view(), name='producto_detalle'),

]

proveedores/urls.py
from django.urls import path
from .views import ProveedorNew
from .views import ProveedorEdit
from .views import ProveedorView
from .views import proveedorInactivar
from .views import ComprasView, compras, CompraDetalleDelete
from .reportes import reporte_compras,imprimir_compra


urlpatterns = [
       path('proveedor/', ProveedorView.as_view(), name='proveedor_list'),
       path('proveedor/new', ProveedorNew.as_view(), name='proveedor_new'),
       path('proveedor/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
       path('proveedor/inactivar/<int:id>', proveedorInactivar, name='proveedor_inactivar'),

       path('compras/', ComprasView.as_view(), name='compras_list'),
       path('compras/new', compras, name='compras_new'),
       path('compras/edit/<int:compra_id>', compras, name = 'compras_edit'),
       path('compras/<int:compra_id>/delete/<int:pk>', CompraDetalleDelete.as_view(), name='compras_del'),

       path('compras/listado', reporte_compras, name = 'compras_print_all'),
       path('compras/<int:compra_id>/imprimir', imprimir_compra, name='compras_print_one')
]

proyectoDs2/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static


#define las urls paternas para incluirlas
urlpatterns = [
    path('',include(('bases.urls', 'bases'), namespace='bases')), #ruta principal
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')), #ruta para inventarios
    path('proveedores/', include(('proveedores.urls', 'proveedores'), namespace='proveedores')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls), #ruta para ventana admin
 ]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proveedores/models.py
from django.db import models
from bases.models import Modelado
from inventario.models import Producto

#para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

# SE CREA EL MODELO PROVEEDOR
class Proveedor(Modelado):
    descripcion=models.CharField(
        max_length=200,
        unique=True
    )
    direccion=models.CharField(
        max_length=250,
        null=True,
        blank=True
    )
    contacto=models.CharField(
        max_length=100
    )
    telefono=models.CharField(
        max_length=10,
        null=True,blank=True
    )
    email=models.CharField(
        max_length=250,
        null=True,
        blank=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Proveedor,self).save()

    class Meta:
        verbose_name_plural = "Proveedores"



#SE CREA EL MODELO COMPRAS ENCABEZADO
class ComprasEncabezado(Modelado):
    fecha_compra = models.DateField(null=True, blank=True)
    observacion = models.TextField(null=True, blank=True)
    no_factura = models.CharField(max_length=100)
    fecha_factura = models.DateField()
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __srt__(self):
        return '{}'.format(self.observacion)

    def save(self):
        self.observacion = self.observacion.upper()
        self.total = self.sub_total - self.descuento
        super(ComprasEncabezado, self).save()

    class Meta:
        verbose_name_plural = "Encabezado Compras"
        verbose_name = "Encabezado Compra"


#SE CREA MODELO COMPRAS DETALLE
class ComprasDetalle(Modelado):
    compra = models.ForeignKey(ComprasEncabezado, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    precio_prv = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    costo = models.FloatField(default=0)

    def __set__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(ComprasDetalle,self).save()

    class Meta:
        verbose_name_plural = "Detalles compras"
        verbose_name = "Detalle Compra"




#MANTENER SIEMPRE ACTUALIZADO ASI SE BORRE O SE AÑADA ALGO A LA LISTA.
@receiver(post_delete, sender=ComprasDetalle)
def detalle_compra_borrar(sender, instance, **kwargs):
    id_producto = instance.producto.id
    id_compra = instance.compra.id

    enc = ComprasEncabezado.objects.filter(pk=id_compra).first()

    if enc:
        sub_total = ComprasDetalle.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        descuento = ComprasDetalle.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        enc.sub_total = sub_total['sub_total__sum']
        enc.descuento=descuento['descuento__sum']
        enc.save()

    prod = Producto.objects.filter(pk=id_producto).first()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()

@receiver(post_save,sender=ComprasDetalle)
def detalle_compra_guardar(sender, instance, **kwargs):
    id_producto = instance.producto.id
    fecha_compra = instance.compra.fecha_compra

    prod = Producto.objects.filter(pk=id_producto).first()

    if prod:
        cantidad = int(prod.existencia) + int(instance.cantidad)
        prod.existencia = cantidad
        prod.ultima_compra = fecha_compra
        prod.save()

proveedores/forms.py
from django import forms
from .models import Proveedor,ComprasEncabezado


class ProveedorForm(forms.ModelForm):
    class Meta:
        model=Proveedor
        fields = ['estado','descripcion','direccion','contacto','telefono','email']
        exclude = ['usuarioModificado', 'fechaModificacion', 'usuarioCreado', 'fechaCreacion']
        widget= {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

    # REVISA QUE NO SE REPITAN DATOS
    def clean(self):
        try:
            sc = Proveedor.objects.get(descripcion=self.cleaned_data['descripcion'].upper())

            if not self.instance.pk:
                print('Registro ya existe')
                raise forms.ValidationError('Registro ya existe')
            elif self.instance.pk!=sc.pk:
                print('cambio no permitido')
                raise forms.ValidationError('Cambio no permitido')
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data




class ComprasEncabezadoForm(forms.ModelForm):
    fecha_compra = forms.DateInput()
    fecha_factura = forms.DateInput()

    class Meta:
        model = ComprasEncabezado
        fields=['proveedor','fecha_compra','observacion','no_factura','fecha_factura','sub_total','descuento','total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

proveedores/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from .models import Proveedor,ComprasEncabezado,ComprasDetalle
from proveedores.forms import ProveedorForm,ComprasEncabezadoForm
from django.contrib.messages.views import SuccessMessageMixin
from bases.views import SinPrivilegios
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse
from inventario.views import Producto
import datetime
from django.db.models import Sum

#CREACION DE MIXIN PARA EVITAR DUPLICADOS
class MixinFormInvalid:
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response


#VISUALIZA LA LISTA DE PROVEEDORES
class ProveedorView(SinPrivilegios, generic.ListView):
    model = Proveedor
    template_name = 'proveedores/proveedor_list.html'
    context_object_name = 'obj'

    # bloquear el permiso de ver la pagina
    permission_required = 'proveedores.view_proveedor'


#CREA UN NUEVO REGISTRO DE PROVEEDOR
class ProveedorNew(SuccessMessageMixin, MixinFormInvalid, SinPrivilegios, generic.CreateView):
    model = Proveedor
    template_name = 'proveedores/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('proveedores:proveedor_list')
    success_message = 'Categoria Creada Satisfactoriamente'
    permission_required = 'proveedores.add_proveedor'

    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        print(self.request.user.id)
        return super().form_valid(form)




#EDITA UN REGISTRO DE PROVEEDOR
class ProveedorEdit(SuccessMessageMixin, MixinFormInvalid, SinPrivilegios, generic.UpdateView):
    model = Proveedor
    template_name = 'proveedores/proveedor_form.html'
    context_object_name = 'obj'
    form_class = ProveedorForm
    success_url = reverse_lazy('proveedores:proveedor_list')
    success_message="Categoria Actualizada Satisfactoriamente"
    permission_required = 'proveedores.change_proveedor'


    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        print(self.request.user.id)
        return super().form_valid(form)


#INACTIVA UN REGISTRO DE PROVEEDOR
@login_required(login_url='/login/')
@permission_required('proveedores.change_proveedor', login_url='bases:sin_privilegios')
def proveedorInactivar(request, id):
    template_name = 'proveedores/inactivar_proveedor.html'
    contexto = {}
    proveedor = Proveedor.objects.filter(pk=id).first()

    if not proveedor:
        return HttpResponse('Proveedor no existe ' + str(id))

    if request.method=='GET':
        contexto={'obj':proveedor}

    if request.method=='POST':
        proveedor.estado = False
        proveedor.save()
        contexto = {'obj':'OK'}
        return HttpResponse('Proveedor ' + proveedor.descripcion + ' inactivado')

    return render(request,template_name,contexto)


# /********************************
# /********************************

#VISUALIZA LA LISTA DE COMPRAS
class ComprasView(SinPrivilegios, generic.ListView):
    model = ComprasEncabezado
    template_name = 'proveedores/compras_list.html'
    context_object_name = 'obj'

    # bloquear el permiso de ver la pagina
    permission_required = 'proveedores.view_comprasencabezado'


@login_required(login_url='/login/')
@permission_required('proveedores.change_comprasencabezado', login_url='bases:sin_privilegios')
def compras(request,compra_id=None):
    template_name='proveedores/compras.html'

    # trae los productos habilitados en la bd de producto enlistados
    prod=Producto.objects.filter(estado=True)
    form_compras={}
    contexto={}

    #se activa cuando se da clic en nuevo o en editar un elemento de la tabla, revisa si hay datos
    #por tomar de los objetos o si vienen vacios.
    if request.method=='GET':
        form_compras=ComprasEncabezadoForm()
        #busca el id asociado para empezar la referencia
        enc = ComprasEncabezado.objects.filter(pk=compra_id).first()
        print("la variable enc tiene contenido:" + str(enc))

        if enc:
            #trae cada uno de los objetos contenidos en detalle
            det = ComprasDetalle.objects.filter(compra=enc)
            print("la variable det tiene contenido:" + str(det))
            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            fecha_factura = datetime.date.isoformat(enc.fecha_factura)
            e = {
                'fecha_compra':fecha_compra,
                'proveedor': enc.proveedor,
                'observacion': enc.observacion,
                'no_factura': enc.no_factura,
                'fecha_factura': fecha_factura,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total
            }

            #SE COLOCAN LOS DATOS LOCALIZADOS EN LOS CAMPOS DEL FORMULARIO
            form_compras = ComprasEncabezadoForm(e)
        else:
            det = None

        contexto = {'productos':prod, 'encabezado':enc, 'detalle': det, 'form_encabezado':form_compras}



    if request.method=='POST':
        print('se activa metodo POST')
        fecha_compra = request.POST.get("fecha_compra")
        observacion = request.POST.get("observacion")
        no_factura = request.POST.get("no_factura")
        fecha_factura = request.POST.get("fecha_factura")
        proveedor = request.POST.get("proveedor")
        sub_total = 0
        descuento = 0
        total = 0

        #COMO EL COMPRA_ID ESTA VACIO, SE PASAN LOS DATOS AGREGADOS.
        if not compra_id:
            print('compra id tiene valor de:' + str(compra_id))
            proveedor = Proveedor.objects.get(pk=proveedor)
            enc = ComprasEncabezado(
                fecha_compra = fecha_compra,
                observacion = observacion,
                no_factura = no_factura,
                fecha_factura = fecha_factura,
                proveedor = proveedor,
                usuarioCreado = request.user
            )
            if enc:
                print('despues de ver que compra_id esta vacio se guarda enc, porque enc esta lleno')
                enc.save()
                compra_id = enc.id

        #CUANDO SE DIRECCIONA PARA EDICION, COMO NO ESTA VACIO,
        else:
            print('el compra_id tiene valor de: ' + str(compra_id))
            enc = ComprasEncabezado.objects.filter(pk=compra_id).first()
            if enc:
                enc.fecha_compra = fecha_compra
                enc.observacion = observacion
                enc.no_factura = no_factura
                enc.fecha_factura = fecha_factura
                enc.unidaddemedida = request.user.id
                enc.save()

        #SI DESPUES DE PASAR LOS DOS CONDICIONALES COMPRA_ID SIGUE ESTANDO NULO, MANDA A LA PRINCIPAL
        if not compra_id:
            return redirect("proveedores:compras_list")

        #TOMA EL RESTO DE DATOS PARA ENVIARLOS
        producto = request.POST.get("id_id_producto")
        cantidad = request.POST.get("id_cantidad_detalle")
        precio = request.POST.get("id_precio_detalle")
        sub_total_detalle = request.POST.get("id_sub_total_detalle")
        descuento_detalle = request.POST.get("id_descuento_detalle")
        total_detalle = request.POST.get("id_total_detalle")

        prod = Producto.objects.get(pk=producto)

        det = ComprasDetalle(
            compra =enc,
            producto = prod,
            cantidad = cantidad,
            precio_prv = precio,
            descuento = descuento_detalle,
            costo = 0,
            usuarioCreado = request.user
        )

        if det:
            print('ME DA LA IMPRESION QUE SIEMPRE ENTRA AQUI')
            det.save()
            sub_total = ComprasDetalle.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento = ComprasDetalle.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            enc.sub_total = sub_total["sub_total__sum"]
            enc.descuento = descuento["descuento__sum"]
            enc.save()

        return redirect("proveedores:compras_edit", compra_id=compra_id)
    print('LUEGO DE QUE CARGA, REALIZA PROCESO DE RENDERIZADO')
    return render(request, template_name, contexto)


# /********************************************
# /********************************************

class CompraDetalleDelete(SinPrivilegios, generic.DeleteView):
    permission_required = 'proveedores.delete_comprasdetalle'
    model = ComprasDetalle
    template_name = 'proveedores/compras_detalle_del.html'
    context_object_name = 'obj'

    def get_success_url(self):
        compra_id=self.kwargs['compra_id']
        return reverse_lazy('proveedores:compras_edit', kwargs={'compra_id':compra_id})

proveedores/templates/proveedores/compras_detalle_del.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        <form method="POST" role="form" class="form-inline"
              action="{% url 'proveedores:compras_del' obj.compra.id obj.pk %}">

            <div class="col-xl-12 col-md-12 mb-12">

                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">

                            <div class="col mr-2">

                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Eliminar Detalle
                                </div>

                                <div class="dropdown-divider"></div>

                                {% csrf_token %}
                                <div class="row">
                                    ¿Eliminar {{ obj.producto }} de compra numero <b>{{ obj.compra.id }}</b> ?
                                </div>

                                <div class="dropdown-divider"></div>

                                <div class="row">
                                    <div class="col">
                                        <button class="btn btn-danger" type="submit"><span class="fa fa-save"></span>Si, Eliminar</button>
                                        <button class="btn btn-success" type="button" onclick="return cerrarModal()">Cancelar</button>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>
</div>
</div>

proveedores/templates/proveedores/compras_list.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
            <div class="fondo-2" style="min-height: 820px;">

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Compras</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item"  href="{% url 'proveedores:compras_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
                      <a class="dropdown-item"  href="{% url 'proveedores:compras_print_all' %}" target="reportes"><i class="fas fa-print"></i> Listado</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay Compras</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                    <th>Id</th>
                    <th>Fecha</th>
                    <th>Observacion</th>
                    <th>No. Factura</th>
                    <th>F. Factura</th>
                    <th>Sub Total</th>
                    <th>Descuento</th>
                    <th>Total</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.fecha_compra }}</td>
                            <td>{{ item.observacion }}</td>
                            <td>{{ item.no_factura }}</td>
                            <td>{{ item.fecha_factura }}</td>
                            <td>{{ item.sub_total }}</td>
                            <td>{{ item.descuento }}</td>
                            <td>{{ item.total }}</td>
                            <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                            <td>
                                <a class="btn btn-warning btn-circle" href="{% url 'proveedores:compras_edit' item.id %}" ><i class="far fa-edit"></i></a>
                                <a class="btn btn-success btn-circle" href="{% url 'proveedores:compras_print_one' item.id %}" ><i class="fas fa-print"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
            </div>
{% endblock page_content %}


{% block js_page %}
    <script>
    //llama a los datatables jquery plugins
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            }
        });
    });

    </script>
{% endblock js_page %}

proveedores/templates/proveedores/proveedor_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        {% if obj %}
            <form method="POST" role="form" class="form-inline" action="{% url 'proveedores:proveedor_edit' obj.pk %}">
        {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'proveedores:proveedor_new' %}">
        {% endif %}

        <div class="col-xl-12 col-md-12 mb-12">

            {#        si el objeto esta para editar, muestra un color, sino muestra otro.#}
            {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
                <div class="card border-left-primary shadow h-100 py-2">
            {% endif %}

            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">

                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar Proveedor {% else %} Nuevo Proveedor {% endif %}
                        </div>

                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}

                        </div>
                        <div class="dropdown-divider"></div>

                        <div class="row">
                            <div class="col ">
                                <button class="btn btn-facebook" type="submit"><span class="fa fa-save"></span> Guardar</button>
                                <button class="btn btn-google" type="button" onclick="return cerrarModal()"> Cancelar</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            </div>
            </div>
        </div>
        </form>
    </div>
</div>


<script>

    {#VALIDACION DE DATOS PARA QUE NO SE REPITAN AL INGRESARLOS#}
    $(function () {

        //se toman los datos del formulario
        var url = $("form").attr("action");

        //se aplica token de seguridad
        var token = jQuery("[name=csrfmiddlewaretoken]").val();

        $("form").submit(function (e) {
            e.preventDefault();
            //se serializan esos datos, quedan en un arreglo
            var formData = $("form").serializeArray();

            $.ajax({
               url:url,
               method:"POST",
               headers: {'X-CSRFToken': token},
               data:formData
            })
            .done(function(r,textStatus, xhr){
              if (xhr.status=200){
                  location.reload();
              }
              else{
                  mensaje(textStatus);
              }
            }).fail(function (error) {
                mensaje(error.responseText);
            });
        });
    });
</script>

{#                error: function (jqXHR, textStatus, errorThrow) {#}
{#                    console.log(textStatus,errorThrow);#}
{#                    mensaje(errorThrow, 'red');#}

proveedores/templates/proveedores/proveedor_list.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
            <div class="fondo-2" style="min-height: 820px;">

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedores</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item"   onclick="return abrirModal('{% url 'proveedores:proveedor_new' %}')" href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay Proveedores</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                    <th>Id</th>
                    <th>Descripcion</th>
                    <th>Direccion</th>
                    <th>Contacto</th>
                    <th>Telefono</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.descripcion }}</td>
                            <td>{{ item.direccion }}</td>
                            <td>{{ item.contacto }}</td>
                            <td>{{ item.telefono }}</td>
                            <td>{{ item.email }}</td>
                            <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                            <td>
                                <button class="btn btn-warning btn-circle" onclick="return abrirModal('{% url 'proveedores:proveedor_edit' item.id %}')"><i class="far fa-edit"></i></button>
                                <button class="btn btn-danger btn-circle" onclick="return abrirModal('{% url 'proveedores:proveedor_inactivar' item.id %}')"><i class="fas fa-ban"></i></button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock page_content %}


{% block js_page %}
   <script>
    //llama a los datatables jquery plugins
    $(document).ready(function () {
        $('.table').DataTable({
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            }
        });
    });

    </script>
{% endblock js_page %}