api/urls.py
from django.urls import path, include
from .views import ProductoList,ProductoDetalle


urlpatterns = [
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>', ProductoDetalle.as_view(), name='producto_detalle'),

]

inventario/urls.py
from django.urls import path
from .views import CategoriaView
from .views import CategoriaNew
from .views import CategoriaEdit
from .views import CategoriaDel
from .views import SubCategoriaView
from .views import SubCategoriaNew
from .views import SubCategoriaEdit
from .views import SubCategoriaDel
from .views import MarcaView
from .views import MarcaNew
from .views import MarcaEdit
from .views import marca_inactivar
from .views import UnidadDeMedidaView
from .views import UnidadDeMedidaNew
from .views import UnidadDeMedidaEdit
from .views import um_inactivar
from .views import ProductoNew
from .views import ProductoView
from .views import ProductoEdit
from .views import producto_inactivar

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/',MarcaView.as_view(), name="marca_list"),
    path('marcas/new', MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>', marca_inactivar, name="marca_inactivar"),

    path('um/',UnidadDeMedidaView.as_view(), name="um_list"),
    path('um/new', UnidadDeMedidaNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>', UnidadDeMedidaEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>', um_inactivar, name='um_inactivar'),

    path('productos/', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>', producto_inactivar, name='producto_inactivar'),

]

proyectoDs2/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static


#define las urls paternas para incluirlas
urlpatterns = [
    path('',include(('bases.urls', 'bases'), namespace='bases')), #ruta principal
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')), #ruta para inventarios
    path('proveedores/', include(('proveedores.urls', 'proveedores'), namespace='proveedores')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls), #ruta para ventana admin
 ]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey

# se crean los parametros que tendra la tabla estado,fechaCreacion,fechaModificacion,usuarioCreado,usuarioModificado
class Modelado(models.Model):
    estado = models.BooleanField(default=True)

    # se actualiza unicamente cuando el registro se cree
    fechaCreacion = models.DateTimeField(auto_now_add=True)

    #se coloca cada vez que haya una modificacion
    fechaModificacion = models.DateTimeField(auto_now=True)

    usuarioCreado = models.ForeignKey(User, on_delete=models.CASCADE)
    usuarioModificado = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True


class Modelado2(models.Model):
    estado = models.BooleanField(default=True)

    # se actualiza unicamente cuando el registro se cree
    fechaCreacion = models.DateTimeField(auto_now_add=True)

    #se coloca cada vez que haya una modificacion
    fechaModificacion = models.DateTimeField(auto_now=True)

    usuarioCreado = UserForeignKey(auto_user_add=True, related_name='+')
    usuarioModificado = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        abstract=True

inventario/models.py
from django.db import models
from bases.models import Modelado

# /*****************************************
# /*****************************************

class Categoria(Modelado):
    descripcion = models.CharField(
        max_length= 100,
        help_text='Descripcion de la categoria',
        unique=True
    )

    #asi es como se va a mostrar, solo descripcion
    def __str__(self):
        return '{}'.format(self.descripcion)

    def _save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()


    class Meta:
        verbose_name_plural = "Categorias"

# /*****************************************
# /*****************************************

class SubCategoria(Modelado):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length= 100,
        help_text='Descripcion de la categoria',
        unique=True
    )

    def __str__(self):
        return '{} : {}'.format(self.categoria.descripcion,self.descripcion)

    def _save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = "SubCategorias"
        unique_together = ('categoria', 'descripcion')


# /*****************************************
# /*****************************************

class Marca(Modelado):
    descripcion = models.CharField(
        max_length= 100,
        help_text='Descripcion de la marca',
        unique=True
    )

    #asi es como se va a mostrar, solo descripcion
    def __str__(self):
        return '{}'.format(self.descripcion)

    def _save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()


    class Meta:
        verbose_name_plural = "Marcas"


# /*****************************************
# /*****************************************

class UnidadDeMedida(Modelado):
    descripcion = models.CharField(
        max_length= 100,
        help_text='Descripcion de la unidad de medida',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadDeMedida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"


# /*****************************************
# /*****************************************

class Producto(Modelado):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)

    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadDeMedida, on_delete=models.CASCADE)
    subCategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barra')

inventario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Categoria
from .forms import CategoriaForm
from .forms import SubCategoriaForm
from .models import SubCategoria
from django.urls import reverse_lazy
from .models import Marca
from .forms import MarcaForm
from .models import UnidadDeMedida
from .forms import UnidadDeMedidaForm
from .models import Producto
from .forms import ProductoForm
from django.contrib import messages
from bases.views import SinPrivilegios
from django.contrib.auth.decorators import login_required, permission_required

# SE APLICO HEREDACION MULTIPLE DE PARTE DE SINPRIVILEGIOS
class CategoriaView(SinPrivilegios, generic.ListView):
    permission_required = 'inventario.view_categoria'
    model = Categoria
    template_name = "inventario/categoria_list.html"
    context_object_name = "obj"



# CREAR UN REGISTRO
class CategoriaNew(SinPrivilegios, generic.CreateView):
    model = Categoria
    template_name = "inventario/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inventario:categoria_list")
    permission_required = 'inventario.add_categoria'

    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        return super().form_valid(form)


# EDITAR UN REGISTRO
class CategoriaEdit(SinPrivilegios, generic.UpdateView):
    model = Categoria
    template_name = "inventario/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inventario:categoria_list")
    permission_required = 'inventario.change_categoria'

    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        return super().form_valid(form)


# BORRAR UN REGISTRO
class CategoriaDel(SinPrivilegios,generic.DeleteView):
    model = Categoria
    template_name = 'inventario/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy("inventario:categoria_list")
    permission_required = 'inventario.delete_categoria'



#/*****************************************
#/*****************************************


#VER REGISTRO SUBCATEGORIA
class SubCategoriaView(SinPrivilegios, generic.ListView):
    model = SubCategoria
    template_name = "inventario/subcategoria_list.html"
    context_object_name = "obj"
    permission_required = 'inventario.view_subcategoria'


# CREAR UN REGISTRO DE SUBCATEGORIA
class SubCategoriaNew(SinPrivilegios, generic.CreateView):
    model = SubCategoria
    template_name = "inventario/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inventario:subcategoria_list")
    permission_required = 'inventario.add_subcategoria'

    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        return super().form_valid(form)


# EDITAR UN REGISTRO EN SUBCATEGORIA
class SubCategoriaEdit(SinPrivilegios, generic.UpdateView):
    model = SubCategoria
    template_name = "inventario/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inventario:subcategoria_list")
    permission_required = 'inventario.change_subcategoria'

    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        return super().form_valid(form)


# BORRAR UN REGISTRO EN SUBCATEGORIA
class SubCategoriaDel(SinPrivilegios,generic.DeleteView):
    model = SubCategoria
    template_name = 'inventario/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy("inventario:subcategoria_list")
    permission_required = 'inventario.delete_subcategoria'



#/*****************************************
#/*****************************************

# MOSTRAR UN REGISTRO DE MARCA
class MarcaView(SinPrivilegios, generic.ListView):
    model = Marca
    template_name = 'inventario/marca_list.html'
    context_object_name = 'obj'
    permission_required = 'inventario.view_marca'


#CREAR UN REGISTRO DE MARCA
class MarcaNew(SinPrivilegios, generic.CreateView):
    model = Marca
    template_name = 'inventario/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:marca_list")
    permission_required = 'inventario.add_marca'


    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        return super().form_valid(form)


#EDITAR UN REGISTRO DE MARCA
class MarcaEdit(SinPrivilegios, generic.UpdateView):
    model = Marca
    template_name = 'inventario/marca_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:marca_list")
    permission_required = 'inventario.change_marca'

    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        return super().form_valid(form)



#INACTIVAR REGISTRO DE MARCA
# -obliga al usuario a loguearse, y si no tiene privilegios a la pagina, muestra mensaje de no permitido.
@login_required(login_url='/login/')
@permission_required('inventario.change_marca', login_url='bases:sin_privilegios')
def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto ={}
    template_name="inventario/catalogos_del.html"

    # si marcar no existe, redirecciones
    if not marca:
        return redirect("inv:marca_list")

    if request.method=='GET':
        contexto={'obj':marca}

    # cuando realice el POST lo cambie a falso y me devuelva a la pagina donde estan las marcas
    if request.method=='POST':
        marca.estado=False
        marca.save()
        messages.success(request,'Marca inactivada')
        return redirect('inventario:marca_list')

    return render(request,template_name,contexto)


#/*****************************************
#/*****************************************

# MOSTRAR UN REGISTRO DE UNIDAD DE MEDIDA
class UnidadDeMedidaView(SinPrivilegios, generic.ListView):
    model = UnidadDeMedida
    template_name = 'inventario/um_list.html'
    context_object_name = 'obj'
    permission_required = 'inventario.view_unidaddemedida'


#CREAR UN REGISTRO DE UNIDAD DE MEDIDA
class UnidadDeMedidaNew(SinPrivilegios, generic.CreateView):
    model = UnidadDeMedida
    template_name = 'inventario/um_form.html'
    context_object_name = 'obj'
    form_class = UnidadDeMedidaForm
    success_url = reverse_lazy("inventario:um_list")
    permission_required = 'inventario.add_unidaddemedida'

    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        return super().form_valid(form)



#EDITAR UN REGISTRO DE UNIDAD DE MEDIDA
class UnidadDeMedidaEdit(SinPrivilegios, generic.UpdateView):
    model = UnidadDeMedida
    template_name = 'inventario/um_form.html'
    context_object_name = 'obj'
    form_class = MarcaForm
    success_url = reverse_lazy("inventario:um_list")
    permission_required = 'inventario.edit_unidaddemedida'

    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        return super().form_valid(form)



#INACTIVAR REGISTRO DE MARCA
@login_required(login_url='/login/')
@permission_required('inventario.change_unidaddemedida', login_url='bases:sin_privilegios')
def um_inactivar(request, id):
    um = UnidadDeMedida.objects.filter(pk=id).first()
    contexto ={}
    template_name="inventario/catalogos_del.html"

    # si marcar no existe, redireccione
    if not um:
        return redirect("inv:um_list")

    if request.method=='GET':
        contexto={'obj':um}

    # cuando realice el POST lo cambie a falso y me devuelva a la pagina donde estan las marcas
    if request.method=='POST':
        um.estado=False
        um.save()
        return redirect('inventario:um_list')

    return render(request,template_name,contexto)



#/*****************************************
#/*****************************************

#MOSTRAR REGISTROS DE PRODUCTOS
class ProductoView(SinPrivilegios, generic.ListView):
    model = Producto
    template_name = 'inventario/producto_list.html'
    context_object_name = 'obj'
    permission_required = 'inventario.view_producto'


#CREA UN PRODUCTO
class ProductoNew(SinPrivilegios, generic.CreateView):
    model = Producto
    template_name = 'inventario/producto_form.html'
    context_object_name = 'obj'
    form_class=ProductoForm
    success_url=reverse_lazy('inventario:producto_list')
    permission_required = 'inventario.add_producto'

    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        return super().form_valid(form)


#EDITA UN PRODUCTO
class ProductoEdit(SinPrivilegios, generic.UpdateView):
    model = Producto
    template_name = 'inventario/producto_form.html'
    context_object_name = 'obj'
    form_class = ProductoForm
    success_url = reverse_lazy('inventario:producto_list')
    permission_required = 'inventario.change_producto'

    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        return super().form_valid(form)


#INACTIVA UN PRODUCTO
@login_required(login_url='/login/')
@permission_required('inventario.change_producto', login_url='bases:sin_privilegios')
def producto_inactivar(request, id):
    prod = Producto.objects.filter(pk=id).first()
    contexto={}
    template_name='inventario/catalogos_del.html'

    if not prod:
        return redirect('inventario:producto_list')

    if request.method=='GET':
        contexto={'obj':prod}

    if request.method=='POST':
        prod.estado=False
        prod.save()
        return redirect('inventario:producto_list')

    return render(request,template_name,contexto)

inventario/templates/inventario/categoria_list.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
    <div class="fondo-2" style="min-height: 820px;">

        <!-- Dropdown Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                         aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Acciones</div>
                        <a class="dropdown-item" href="{% url 'inventario:categoria_new' %}"><i
                                class="far fa-calendar-plus"></i> Nueva</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% if not obj %}
                    <div class="alert alert-info">No hay Categorias</div>
                {% else %}
                    <table class="table table-striped table-hover">
                        <thead>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>F. creado</th>
                        <th>F. Modificado</th>
                        <th class="all">Acciones</th>
                        </thead>
                        <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fechaCreacion|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fechaModificacion|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inventario:categoria_edit' item.id %}"
                                       class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inventario:categoria_del' item.id %}"
                                       class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock page_content %}


{% block js_page %}
    <script>
        //llama a los datatables jquery plugins
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "buttons": {
                        "copy": "Copiar",
                        "colvis": "Visibilidad"
                    }
                }
            });
        });

    </script>
{% endblock js_page %}

inventario/templates/inventario/marca_list.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
    <div class="fondo-2" style="min-height: 820px;">

        <!-- Dropdown Card Example -->
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                         aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Acciones</div>
                        <a class="dropdown-item" href="{% url 'inventario:marca_new' %}"><i
                                class="far fa-calendar-plus"></i> Nueva</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                {% if not obj %}
                    <div class="alert alert-info">No hay Marca</div>
                {% else %}
                    <table class="table table-striped table-hover">
                        <thead>
                        <th>Id</th>
                        <th>Descripcion</th>
                        <th>Estado</th>
                        <th>F. creado</th>
                        <th>F. Modificado</th>
                        <th class="all">Acciones</th>
                        </thead>
                        <tbody>
                        {% for item in obj %}
                            <tr>
                                <td>{{ item.id }}</td>
                                <td>{{ item.descripcion }}</td>
                                <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                                <td>{{ item.fechaCreacion|date:"d/m/Y H:i:s" }}</td>
                                <td>{{ item.fechaModificacion|date:"d/m/Y H:i:s" }}</td>
                                <td>
                                    <a href="{% url 'inventario:marca_edit' item.id %}"
                                       class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                    <a href="{% url 'inventario:marca_inactivar' item.id %}"
                                       class="btn btn-danger btn-circle" role="button"><i class="fas fa-ban"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock page_content %}


{% block js_page %}
    <script>
        //llama a los datatables jquery plugins
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "buttons": {
                        "copy": "Copiar",
                        "colvis": "Visibilidad"
                    }
                }
            });
        });

    </script>
{% endblock js_page %}

inventario/templates/inventario/subcategoria_form.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
        <div class="fondo-3" style="min-height: 850px;">

        <form method="POST" class="form-inline pt-3">
            {% csrf_token %}
            <div class="col-xl-6 col-md-6 mb-6">

                {#        si el objeto esta para editar, muestra un color, sino muestra otro.#}
                {% if obj %}
                    <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                    <div class="card border-left-primary shadow h-100 py-2">
                {% endif %}

                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">

                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar Sub-Categoria {% else %} Nueva Sub-Categoria {% endif %}
                            </div>

                            <div class="dropdown-divider"></div>
                            <div class="row">

                                <div class="col-5">

                                    <div class="input-group">
{#                                                                            {% if obj %}#}
{#                                                                                <input type="text" name="categoria" maxlength="100" class="form-control"#}
{#                                                                                       required id="id_categoria" placeholder="Categoria"#}
{#                                                                                       value="{% if obj %} {{ obj.categoria }} {% endif %}">#}
{#                                                                            {% endif %}#}
                                        {{ form.categoria }}
                                    </div>
                                </div>

                                <div class="col-5">
                                    <div class="input-group">
                                        <input type="text" name="descripcion" maxlength="100" class="form-control"
                                               required id="id_descripcion" placeholder="Descripción"
                                               value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control ml-2" id="id_estado"
                                                {% if obj.estado %} checked {% endif %}>
                                    </div>
                                </div>

                            </div>
                            <div class="dropdown-divider"></div>

                            <div class="row">
                                <div class="col">
                                    <button class="btn btn-facebook" type="submit"><span class="fa fa-save"></span> Guardar
                                    </button>
                                    <a href="{% url 'inventario:subcategoria_list' %}" class="btn btn-google"><span
                                            class="fa fa-undo"></span> Cancelar</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                </div>
                </div>
            </div>
        </form>
    </div>
{% endblock page_content %}


{% block js_page %}
    <script>
        $('footer').hide();
    </script>
{% endblock js_page %}