api/urls.py
from django.urls import path, include
from .views import ProductoList,ProductoDetalle


urlpatterns = [
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>', ProductoDetalle.as_view(), name='producto_detalle'),

]

facturacion/urls.py
from django.urls import path
from .views import ClienteView,ClienteNew,ClienteEdit,clienteInactivar,FacturaView,facturaRealizar,ProductoView,borrar_detalle_factura
from .reportes import imprimir_factura_recibo

urlpatterns = [
    path('clientes/', ClienteView.as_view(), name='cliente_list'),
    path('clientes/new', ClienteNew.as_view(), name='cliente_new'),
    path('clientes/<int:pk>', ClienteEdit.as_view(), name='cliente_edit'),
    path('clientes/estado/<int:id>', clienteInactivar, name="cliente_inactivar"),

    path('facturas/', FacturaView.as_view(), name='factura_list'),
    path('facturas/new', facturaRealizar, name='factura_new'),
    path('facturas/edit/<int:id>', facturaRealizar, name='factura_edit'),

    path('facturas/buscar-producto', ProductoView.as_view(), name='factura_producto'),

    path('facturas/borrar-detalle/<int:id>', borrar_detalle_factura, name='factura_borrar_detalle'),

    path('facturas/imprimir/<int:id>', imprimir_factura_recibo, name='factura_imprimir_one'),

]

proyectoDs2/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static


#define las urls paternas para incluirlas
urlpatterns = [
    path('',include(('bases.urls', 'bases'), namespace='bases')), #ruta principal
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')), #ruta para inventarios
    path('proveedores/', include(('proveedores.urls', 'proveedores'), namespace='proveedores')),
    path('facturacion/', include(('facturacion.urls', 'facturacion'), namespace='facturacion')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls), #ruta para ventana admin
 ]

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

facturacion/models.py
from django.db import models
from bases.models import Modelado, Modelado2
from inventario.models import Producto

#para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

class Cliente(Modelado):
    # SE CREA UNA LISTA CON DOS DATOS A INCLUIR
    NAT = 'Natural'
    JUR = 'Juridica'
    TIPO_CLIENTE = [
        (NAT, 'Natural'),
        (JUR, 'Juridica')
    ]

    nombres = models.CharField(
        max_length=100
    )
    apellidos = models.CharField(
        max_length=100
    )
    celular = models.CharField(
        max_length=20,
        null=True,
        blank=True,
    )
    tipo = models.CharField(
        max_length=10,
        choices=TIPO_CLIENTE,
        default=NAT,
    )

    def __str__(self):
        return '{} {}'.format(self.apellidos, self.nombres)

    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente, self).save()

    class Meta:
        verbose_name_plural = 'Clientes'






    # **********************************************


class FacturaEncabezado(Modelado2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        self.total = self.sub_total - self.descuento
        super(FacturaEncabezado, self).save()

    class Meta:
        verbose_name_plural = 'Encabezado Facturas'
        verbose_name = 'Encabezado Factura'
        permissions = [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado')]




class FacturaDetalle(Modelado2):
    factura = models.ForeignKey(FacturaEncabezado, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    precio = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def __set__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        super(FacturaDetalle, self).save()

    class Meta:
        verbose_name_plural = 'Detalles Facturas'
        verbose_name = 'Detalle Factura'
        permissions = [('sup_caja_facturadet','Permisos de Supervisor de Caja Detalle')]


@receiver(post_save, sender=FacturaDetalle)
def detalle_facturacion_guardar(sender,instance, **kwargs):
    factura_id = instance.factura_id
    producto_id = instance.producto_id

    enc = FacturaEncabezado.objects.get(pk=factura_id)
    if enc:
        sub_total = FacturaDetalle.objects.filter(factura=factura_id)\
            .aggregate(sub_total=Sum('sub_total')).get('sub_total',0.00)

        descuento = FacturaDetalle.objects.filter(factura=factura_id)\
            .aggregate(descuento=Sum('descuento')).get('descuento',0.00)

        enc.sub_total = sub_total
        enc.descuento = descuento
        enc.save()

    prod = Producto.objects.filter(pk=producto_id).first()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()

facturacion/forms.py
from django import forms
from .models import Cliente



class ClienteForm(forms.ModelForm):
    class Meta:
        model=Cliente
        fields = ['nombres','apellidos','tipo','celular','estado']
        exclude = ['usuarioModificado', 'fechaModificacion', 'usuarioCreado', 'fechaCreacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

facturacion/views.py
from django.shortcuts import render, redirect
from .models import Cliente,FacturaDetalle,FacturaEncabezado
from bases.views import SinPrivilegios
from django.views import generic
from .forms import ClienteForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from datetime import datetime
from inventario.views import ProductoView,Producto
from django.contrib import messages
from django.contrib.auth import authenticate


class ClienteView(SinPrivilegios, generic.ListView):
    model = Cliente
    template_name = 'facturacion/cliente_list.html'
    context_object_name = 'obj'
    permission_required = 'facturacion.view_cliente'


#/************************************************************************************
#/*********************SUPER CLASES**************************************************
#/************************************************************************************

class VistaBaseCreate(SuccessMessageMixin, SinPrivilegios, generic.CreateView):
    model = Cliente
    context_object_name = 'obj'
    success_message = 'Operacion Satisfactoria'

    def form_valid(self, form):
        form.instance.usuarioCreado = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin, SinPrivilegios, generic.UpdateView):
    model = Cliente
    context_object_name = 'obj'
    success_message = 'Operacion Satisfactoria'

    def form_valid(self, form):
        form.instance.usuarioModificado = self.request.user.id
        return super().form_valid(form)

#/************************************************************************************
#/************************************************************************************
#/************************************************************************************


class ClienteNew(VistaBaseCreate):
    template_name = 'facturacion/cliente_form.html'
    form_class = ClienteForm
    success_url = reverse_lazy('facturacion:cliente_list')
    permission_required = 'facturacion.add_cliente'

class ClienteEdit(VistaBaseEdit):
    template_name = 'facturacion/cliente_form.html'
    form_class = ClienteForm
    success_url = reverse_lazy('facturacion:cliente_list')
    permission_required = 'facturacion.chage_cliente'


@login_required(login_url='/login/')
@permission_required('facturacion.change_cliente', login_url='/login/')
def clienteInactivar(request, id):
    cliente = Cliente.objects.filter(pk=id).first()

    if request.method=="POST":
        if cliente:
            cliente.estado = not cliente.estado
            cliente.save()
            return HttpResponse('OK')
        return HttpResponse('FAIL')

    return HttpResponse('FAIL')



#***************FACTURAS*****************
class FacturaView(SinPrivilegios, generic.ListView):
    model = FacturaEncabezado
    template_name = 'facturacion/factura_list.html'
    context_object_name = 'obj'
    permission_required = 'facturacion.view_facturaencabezado'



@login_required(login_url='/login/')
@permission_required('facturacion.change_facturaencabezado', login_url='bases:sin_privilegios')
def facturaRealizar(request, id=None):
    template_name = 'facturacion/facturas.html'

    # encabezado = {
    #     'fecha':datetime.today()
    # }
    detalle = {}
    clientes = Cliente.objects.filter(estado=True)

    if request.method == "GET":
        enc = FacturaEncabezado.objects.filter(pk=id).first()
        print('inicial enc ' + str(enc))
        if not enc:
            print('NO HAY ENC (GET) ' + str(enc))
            encabezado = {
                'id':0,
                'fecha':datetime.today(),
                'cliente':0,
                'sub_total':0.00,
                'descuento':0.00,
                'total':0.00
            }
            detalle = None
        else:
            print('SI HAY ENC (GET) ' + str(enc))
            encabezado = {
                'id': enc.id,
                'fecha': enc.fecha,
                'cliente': enc.cliente,
                'sub_total': enc.sub_total,
                'descuento': enc.descuento,
                'total': enc.total
            }
            detalle = FacturaDetalle.objects.filter(factura=enc)

        contexto={"enc":encabezado, "det":detalle, "clientes":clientes}



    if request.method == "POST":
        cliente = request.POST.get('encabezado_cliente')
        print('el cliente para POST es: ' + cliente)
        fecha = request.POST.get('fecha')
        cli = Cliente.objects.get(pk=cliente)

        if not id:
            print('no existe un id, por lo tanto toma datos de factura encabezado')
            enc = FacturaEncabezado(
                cliente = cli,
                fecha = fecha
            )
            print('ahora se imprime a encabezado: ' + str(enc))
            if enc:
                enc.save()
                id = enc.id
        else:
            enc = FacturaEncabezado.objects.filter(pk=id).first()
            print('entra en el else y tiene por valor a enc ' + str(enc))
            if enc:
                print('llega a guardar el dato en enc' + str(enc))
                enc.cliente = cli
                enc.save()

        if not id:
            messages.error(request,'No puedo continuar, no se detecta el No de Factura')
            return redirect("facturacion:factura_list")

        codigo = request.POST.get('codigo')
        cantidad = request.POST.get('cantidad')
        precio = request.POST.get('precio')
        sub_total = request.POST.get('sub_total_detalle')
        descuento = request.POST.get('descuento_detalle')
        total = request.POST.get('total_detalle')
        print('finalmente estos son datas' + str(codigo) + ':' + str(cantidad) + ':' + str(precio) + ':' + str(sub_total) + ':' + str(descuento) + ':' + str(total))

        prod = Producto.objects.get(codigo=codigo)
        detalle = FacturaDetalle(
            factura = enc,
            producto = prod,
            cantidad = cantidad,
            precio = precio,
            sub_total = sub_total,
            descuento = descuento,
            total = total
        )

        if detalle:
            detalle.save()

        return redirect("facturacion:factura_edit", id=id)

    return render(request,template_name,contexto)



class ProductoView(ProductoView):
    template_name='facturacion/buscar_producto.html'


def borrar_detalle_factura(request, id):
    template_name = 'facturacion/factura_borrar_detalle.html'

    det = FacturaDetalle.objects.get(pk=id)

    if request.method == 'GET':
        context={'det':det}

    if request.method == "POST":
        usr = request.POST.get('usuario')
        pas = request.POST.get('pass')

        user = authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o clave incorrecta")

        if not user.is_active:
            return HttpResponse("Usuario inactivo")

        if user.is_superuser or user.has_perm("fac.sup_caja_facturadet"):
            # se coloca el id en vacio para que asi cree uno nuevo para hacer la parte negativa que resta
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()

            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")

    return render(request,template_name,context)

facturacion/templates/facturacion/buscar_producto.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Buscar Producto
                            </div>
                            <div class="dropdown-divider"></div>

                            <div class="row">
                                <table
                                        id="tblProducto"
                                        data-pagination="true"
                                        data-search="true"
                                        data-show-columns="true"
                                        data-show-fullscreen="true"
                                        data-locale="es-NI"
                                >
                                    <thead>
                                    <th data-sortable="true" data-field="id">id</th>
                                    <th data-sortable="true" data-field="codigo">Codigo</th>
                                    <th data-sortable="true" data-field="codigo_barra">Barra</th>
                                    <th data-field="descripcion">Descripcion</th>
                                    <th data-field="existencia">Existencia</th>
                                    <th data-field="precio">Precio</th>
                                    <th class="all">Acciones</th>
                                    </thead>
                                    <tbody>
                                    {% for item in obj %}
                                        <tr>
                                            <td>{{ item.id }}</td>
                                            <td>{{ item.codigo }}</td>
                                            <td>{{ item.codigo_barra }}</td>
                                            <td>{{ item.descripcion }}</td>
                                            <td>{{ item.existencia }}</td>
                                            <td>{{ item.precio }}</td>
                                            <td>
                                                {% if item.existencia > 0 and item.estado %}
                                                <button class="btn btn-warning btn-circle" id="btnSelect"
                                                        onclick="seleccionarProducto({{ item.id }}, '{{ item.codigo }}',
                                                                '{{ item.descripcion }}', {{ item.precio }})"><i
                                                        class="far fa-hand-pointer"></i></button>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button class="btn btn-success" type="button" id="btnCancelar">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% block js_page %}
    <script>
        $(function () {
            $("#btnCancelar").click(function (e) {
                e.preventDefault();
                cerrarModal();
            });
        });
        $('#tblProducto').bootstrapTable();

        function seleccionarProducto(id, codigo, descripcion, precio) {
            $("#codigo").val(codigo);
            $("#descripcion").val(descripcion);
            $("#precio").val(precio);
            $("#btnCancelar").click();
            $("#codigo").select();
            $("#codigo").focus();
        }
    </script>
{% endblock %}

facturacion/templates/facturacion/cliente_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">

        {% if obj %}
            <form method="POST" role="form" class="form-inline" action="{% url 'facturacion:cliente_edit' obj.pk %}">
        {% else %}
            <form method="POST" role="form" class="form-inline" action="{% url 'facturacion:cliente_new' %}">
        {% endif %}

        <div class="col-xl-12 col-md-12 mb-12">

            {#        si el objeto esta para editar, muestra un color, sino muestra otro.#}
            {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
                <div class="card border-left-primary shadow h-100 py-2">
            {% endif %}

            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">

                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar Cliente {% else %} Nuevo Cliente {% endif %}
                        </div>

                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}

                        </div>
                        <div class="dropdown-divider"></div>

                        <div class="row">
                            <div class="col">
                                <button class="btn btn-facebook" type="submit"><span class="fa fa-save"></span> Guardar</button>
                                <button class="btn btn-google" type="button" onclick="return cerrarModal()"> Cancelar</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            </div>
            </div>
        </div>
        </form>
    </div>
</div>

facturacion/templates/facturacion/cliente_list.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
            <div class="fondo-2" style="min-height: 820px;">

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item" onclick="return abrirModal('{% url 'facturacion:cliente_new' %}')"
                       href="#"><i class="far fa-calendar-plus"></i> Nuevo</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info">No hay Clientes</div>
            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                    <th>Id</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Tipo</th>
                    <th>Telefono</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.nombres }}</td>
                            <td>{{ item.apellidos }}</td>
                            <td>{{ item.tipo }}</td>
                            <td>{{ item.celular }}</td>
                            <td onclick="inactivar({{ item.id }})">
                                {% if item.estado %}
                                    <i class="far fa-thumbs-up text-primary" style="cursor: pointer"></i>
                                {% else %}
                                    <i class="far fa-thumbs-down text-danger" style="cursor: pointer"></i>
                                {% endif %}
                            </td>
                            <td>
                                <button class="btn btn-warning btn-circle"
                                        onclick="return abrirModal('{% url 'facturacion:cliente_edit' item.pk %}')"><i
                                        class="far fa-edit"></i></button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
            </div>
{% endblock page_content %}


{% block js_page %}
    <script>
        //Inactivar Usuario
        function inactivar(id) {
            var data = {id: id};
            data = JSON.stringify(data);
            var token = '{{ csrf_token }}';


            $.ajax({
                headers: {"X-CSRFToken": token},
                type: "POST",
                url: "/facturacion/clientes/estado/" + id,
                data: data,
                success: function (response) {
                    if (response === 'OK') {
                        location.reload();
                    }
                    else {mensaje("Error de cambio de estado");}
                },
                error: function(jqXHR, textStatus, errorThrow){
                    console.log(textStatus, errorThrow);
                    mensaje(errorThrow, 'red');
                    cerrarModal();
                }
            });
        }



        //llama a los datatables jquery plugins
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "buttons": {
                        "copy": "Copiar",
                        "colvis": "Visibilidad"
                    }
                }
            });
        });

    </script>
{% endblock js_page %}

facturacion/templates/facturacion/factura_borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{ det.producto.descripcion }}</b> de factura <b>{{ det.factura.id }}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" class="form-control" id="usuario" required>
    </div>

    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

facturacion/templates/facturacion/factura_list.html
{% extends 'base/baseTotalidad.html' %}

{#anula los bloques de contenido#}
{% block page_content %}
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Facturas</h6>

        </div>


        <!-- Card Body -->
        <div class="card-body">

            <div class="row text-center">
                <div class="col-md-4">
                    <label >Fecha inicio</label>
                    <input type="text" class="form-class" name="f1" id="f1" readonly>
                </div>
                <div class="col-md-4">
                     <label >Fecha fin</label>
                    <input type="text" class="form-class" name="f2" id="f2" readonly>
                </div>
                <div class="col-md-4">
                    <button class="btn btn-warning" type="button" id="btnPrint"><i class="fas fa-print"></i> Imprimir</button>
                </div>
            </div>

            <hr>

            <div class="buttons-toolbar mb-3">
                <a href="{% url 'facturacion:factura_new' %}" class="btn btn-success"><i class="far fa-plus-square"></i> Nueva Factura</a>
            </div>
            {% if not obj %}
                <div class="alert alert-info">No hay Facturas</div>

            {% else %}
                <table class="table table-striped table-hover">
                    <thead>
                    <th>No. Factura</th>
                    <th>Cliente</th>
                    <th>Total</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.cliente }}</td>
                            <td>{{ item.total }}</td>
                            <td onclick="inactivar({{ item.id }})">
                                {% if item.estado %}
                                    <i class="far fa-thumbs-up text-primary" style="cursor: pointer"></i>
                                {% else %}
                                    <i class="far fa-thumbs-down text-danger"></i>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'facturacion:factura_edit' item.id %}"
                                   class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock page_content %}






{% block js_page %}
    <script>

        //llama a los datatables jquery plugins
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "buttons": {
                        "copy": "Copiar",
                        "colvis": "Visibilidad"
                    }
                }
            });
        });

        {#ACTIVA LA FECHA EN UN INPUT PARA SELECCIONAR#}
        $(function () {
            $("#f1, #f2").datetimepicker({
                format: 'Y-m-d',
                timepicker:false
            });
        });

    </script>
{% endblock js_page %}